import { ArrowLeft, Download, FileCheck2, ListChecks, Scale, ShieldAlert, Sparkles, TrendingUp, Users } from "lucide-react";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import SandboxFrame from "../../components/sandbox/SandboxFrame";
import { sandboxApi, type SandboxRun } from "../../lib/sandboxApi";

export default function SandboxReportView({ loading = false, run }: { loading?: boolean; run: SandboxRun }) {
  const report = run.report; const navigate = useNavigate(); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  async function download() { if (busy) return; setBusy("pdf"); setError(""); try { const created = await sandboxApi.createExport(run.id, "pdf"); const blob = await sandboxApi.downloadExport(created.download_url); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${run.name || run.product.name || "商业沙盘报告"}.pdf`; anchor.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "PDF 下载失败，请稍后重试。"); } finally { setBusy(""); } }
  async function growth() { if (busy) return; setBusy("growth"); try { const result = await sandboxApi.createGrowthHandoff(run.id); navigate(result.url); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "增长测算承接失败。"); } finally { setBusy(""); } }
  if (loading || !report) return <SandboxFrame copilotMode="report"><section className="sb-empty-panel sb-report-empty"><FileCheck2 size={32} /><h1>{loading ? "正在加载推演报告" : "报告尚未生成"}</h1><p>完成至少一个角色后才会生成结构化报告。</p><Link to={`/sandbox-runs/${run.id}`}><ArrowLeft size={16} />返回本轮推演</Link></section></SandboxFrame>;
  return <SandboxFrame copilotMode="report" copilotProject={run.product.name}><header className="sb-report-heading"><div><div className="sb-breadcrumb"><Link to="/sandbox/history">商业沙盘</Link><span>/</span><strong>推演报告</strong><em>模型推演</em>{run.status === "partial" ? <em>部分完成</em> : null}</div><h1>{run.name || run.product.name}</h1><p>参与角色：{run.roles.length} · 假设：{report.assumptions.length} · 缺失角色：{report.missing_roles.length}</p></div><button className="sb-export-button" disabled={Boolean(busy)} onClick={() => void download()} type="button"><Download size={16} />{busy === "pdf" ? "下载中..." : "导出 PDF"}</button></header>
    <section className="sb-report-metrics"><article className="sb-metric-card is-purple"><Sparkles size={21} /><small>综合可行性</small><strong>{report.feasibility.score}<em>/100</em></strong><p>{report.feasibility.level}</p></article><article className="sb-metric-card is-blue"><TrendingUp size={21} /><small>消费概率</small><strong>{report.purchase_probability.value_pct}<em>%</em></strong><p>模型推演</p></article><article className="sb-metric-card is-orange"><ShieldAlert size={21} /><small>风险项</small><strong>{report.risk.length}</strong><p>需真实验证</p></article><article className="sb-metric-card is-green"><Scale size={21} /><small>明确分歧</small><strong>{report.disagreements.length}</strong><p>不做简单平均</p></article></section>
    <section className="sb-report-conclusion"><header><Sparkles size={18} /><h2>核心结论</h2></header><p>{report.summary}</p><small>{report.feasibility.basis}</small></section>
    <div className="sb-report-two-col"><section className="sb-report-section sb-insight-section is-opportunity"><header><TrendingUp size={18} /><h2>机会分析</h2></header><div>{report.opportunity.map((item) => <article key={item.point}><strong>{item.point}</strong><p>{item.reason}</p></article>)}</div></section><section className="sb-report-section sb-insight-section is-risk"><header><ShieldAlert size={18} /><h2>风险分析</h2></header><div>{report.risk.map((item) => <article key={item.point}><strong>{item.point}</strong><p>{item.reason}</p><small>缓解：{item.mitigation}</small></article>)}</div></section></div>
    <section className="sb-report-section"><header><Users size={18} /><h2>角色观点</h2></header><div className="sb-report-role-grid">{report.role_takeaways.map((item) => <article key={item.role}><strong>{item.role} · {item.stance === "oppose" ? "反对" : item.stance === "support" ? "支持" : "中立"}</strong><p>{item.key_points.join("；")}</p></article>)}</div>{report.missing_roles.length ? <p className="sb-inline-error">缺失角色：{report.missing_roles.join("、")}</p> : null}</section>
    <section className="sb-report-section"><header><Scale size={18} /><h2>观点分歧</h2></header>{report.disagreements.length ? report.disagreements.map((item) => <article className="sb-report-conclusion" key={item.topic}><strong>{item.topic}</strong><p>{item.views.map((view) => `${view.role}：${view.point}`).join("；")}</p><small>需要决策：{item.decision_needed}</small></article>) : <p className="sb-muted-copy">本轮没有结构化分歧。</p>}</section>
    <section className="sb-report-section"><header><ListChecks size={18} /><h2>行动建议</h2></header><div className="sb-action-plan">{[...report.advice].sort((a, b) => a.priority - b.priority).map((item) => <article key={`${item.priority}-${item.action}`}><b>{item.priority}</b><div><strong>{item.action}</strong><p>{item.why}</p></div><small>{item.effort}</small></article>)}</div></section>
    <footer className="sb-report-footer"><Link to={`/sandbox-runs/${run.id}`}><ArrowLeft size={16} />返回本轮推演</Link><button disabled={Boolean(busy)} onClick={() => void growth()} type="button">去增长测算</button><Link className="is-primary" to="/sandbox/history">查看历史</Link></footer>{error ? <p className="sb-inline-error" role="alert">{error}</p> : null}
  </SandboxFrame>;
}
