import { ArrowLeft, ArrowRight, FileText, History, Search, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import SandboxFrame from "../../components/sandbox/SandboxFrame";
import { sandboxApi, type SandboxRun, type SandboxRunStatus } from "../../lib/sandboxApi";

export default function SandboxHistoryView() {
  const [runs, setRuns] = useState<SandboxRun[]>([]); const [page, setPage] = useState(1); const [status, setStatus] = useState<"" | SandboxRunStatus>(""); const [product, setProduct] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; const timer = window.setTimeout(() => { setLoading(true); void sandboxApi.listRuns({ page, limit: 20, status: status || undefined, product }).then((payload) => { if (active) setRuns(payload.runs ?? []); }).catch((requestError) => { if (active) setError(requestError instanceof Error ? requestError.message : "历史记录加载失败。"); }).finally(() => { if (active) setLoading(false); }); }, 150); return () => { active = false; window.clearTimeout(timer); }; }, [page, product, status]);
  return <SandboxFrame copilotMode="history"><header className="sb-history-heading"><div className="sb-breadcrumb"><Link to="/sandbox">商业沙盘</Link><span>/</span><strong>历史推演</strong><small>全部记录不限条数、不限时长</small></div></header><section className="sb-history-notice"><span><History size={22} /></span><div><strong>服务端历史记录</strong><p>筛选、分页和状态均来自 V1.2 接口，不会锁定旧记录。</p></div><Link to="/sandbox">开始新推演</Link></section><section className="sb-history-filters"><label className="sb-search-field"><Search size={16} /><input aria-label="搜索产品名称" onChange={(event) => { setProduct(event.target.value); setPage(1); }} placeholder="搜索产品名称" value={product} /></label><label><span>状态</span><select aria-label="全部状态" onChange={(event) => { setStatus(event.target.value as "" | SandboxRunStatus); setPage(1); }} value={status}><option value="">全部状态</option><option value="done">已完成</option><option value="partial">部分完成</option><option value="running">推演中</option><option value="ready">准备就绪</option><option value="clarifying">补充信息</option><option value="failed">失败</option></select></label></section><section className="sb-history-table"><header><span>项目名称</span><span>参与角色</span><span>推演时间</span><span>状态</span><span>可行性</span><span>消费概率</span><span>操作</span></header>{loading ? <div className="sb-table-state"><Sparkles size={20} />正在读取推演记录...</div> : runs.length ? runs.map((run) => <HistoryRow key={run.id} run={run} />) : <div className="sb-table-state"><FileText size={22} /><strong>没有符合条件的推演记录</strong><span>调整筛选条件，或开始一轮新的商业沙盘。</span><Link to="/sandbox">开始新推演<ArrowRight size={15} /></Link></div>}</section><footer className="sb-history-pagination"><button aria-label="上一页" disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))} type="button"><ArrowLeft size={16} /></button><b>{page}</b><button aria-label="下一页" disabled={runs.length < 20} onClick={() => setPage((value) => value + 1)} type="button"><ArrowRight size={16} /></button></footer>{error ? <p className="sb-inline-error" role="alert">{error}</p> : null}</SandboxFrame>;
}
function HistoryRow({ run }: { run: SandboxRun }) { const terminal = ["done", "partial"].includes(run.status); const href = terminal ? `/sandbox-runs/${run.id}/report` : run.status === "running" || run.status === "failed" ? `/sandbox-runs/${run.id}` : `/sandbox/new?run=${run.id}&step=${run.status === "clarifying" ? 2 : 3}`; return <article><div className="sb-history-project"><span>{run.product.name.slice(0, 1) || "沙"}</span><div><strong>{run.name || run.product.name}</strong><small>{run.product.selling_point || run.context.target_customer || "待补充"}</small></div></div><div className="sb-history-roles"><em>{run.roles.length} 个角色</em></div><time>{formatDate(run.created_at)}</time><span className={`sb-status-pill is-${run.status}`}>{statusLabel(run.status)}</span><strong className="sb-history-score">{run.report ? run.report.feasibility.score : "--"}</strong><span>{run.report ? `${run.report.purchase_probability.value_pct}%` : "--"}</span><Link to={href}>{terminal ? "查看报告" : "继续处理"}</Link></article>; }
function statusLabel(value: SandboxRunStatus) { return ({ draft: "草稿", clarifying: "补充信息", ready: "准备就绪", running: "推演中", partial: "部分完成", done: "已完成", failed: "失败", ai_no_result: "无有效结果" } as const)[value]; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("zh-CN", { hour12: false, month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }); }
